---
steps:
  - name: hello
    image: alpine:latest
    environment:
      GREETING: "Hello"
    commands:
      - echo "${GREETING} from Woodpecker 3.x!"
      - echo "Repository: ${CI_REPO}"
      - echo "Branch: ${CI_COMMIT_BRANCH}"
      - echo "Commit: ${CI_COMMIT_SHA}"
