# Docker Compose configuration for Discord Emoji Bot

services:
  discord-emoji-bot:
    build: .
    container_name: emoji-bot
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GUILD_ID=${GUILD_ID:-}
    networks:
      - bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bot-network:
    driver: bridge
