# Alternative: Using Host Docker Socket (More Reliable on Oracle Cloud)
# This approach uses the host's Docker daemon instead of DinD

when:
  - event: [push, tag]
    branch: main

steps:
  # Pre-deployment checks
  - name: pre-deploy-check
    image: python:3.11-slim
    environment:
      DISCORD_BOT_TOKEN:
        from_secret: DISCORD_BOT_TOKEN
      OPENAI_API_KEY:
        from_secret: OPENAI_API_KEY
    commands:
      - echo "🔍 Running pre-deployment checks for Discord Emoji Bot..."
      - |
        if [ -z "$DISCORD_BOT_TOKEN" ]; then
          echo "❌ DISCORD_BOT_TOKEN is required for Discord bot deployment"
          exit 1
        fi
      - |
        if [ -z "$OPENAI_API_KEY" ]; then
          echo "❌ OPENAI_API_KEY is required for DALL-E emoji generation"
          exit 1
        fi
      - echo "✅ Discord and OpenAI environment variables validated"

  # Build production image using host Docker
  - name: build-production
    image: docker:24-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "🏗️ Building production Docker image for Discord Emoji Bot..."
      - docker info  # Test connection
      - docker build -t discord-emoji-bot:production-${CI_COMMIT_SHA} .
      - docker tag discord-emoji-bot:production-${CI_COMMIT_SHA} discord-emoji-bot:production-latest
      - echo "✅ Discord Emoji Bot production image built!"

  # Deploy using docker-compose
  - name: deploy-with-compose
    image: docker:24-cli
    detach: true
    environment:
      DISCORD_BOT_TOKEN:
        from_secret: DISCORD_BOT_TOKEN
      OPENAI_API_KEY:
        from_secret: OPENAI_API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - export DISCORD_BOT_TOKEN="${DISCORD_BOT_TOKEN}"
      - export OPENAI_API_KEY="${OPENAI_API_KEY}"
      - echo "🚀 Deploying Discord Emoji Bot with docker-compose..."
      - |
        # Install docker-compose from Alpine package manager
        apk add --no-cache docker-compose
      - |
        # Update the docker-compose.yml to use the new image
        sed -i "s|build: \.|image: discord-emoji-bot:production-${CI_COMMIT_SHA}|" docker-compose.yml
      - |
        # Deploy the Discord bot application
        docker-compose down || true
        docker-compose up -d
      - echo "✅ Discord Emoji Bot deployment completed!"

  # Health check
  - name: health-check
    image: docker:24-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo "🏥 Running health checks for Discord Emoji Bot..."
      - sleep 45  # Wait for Discord bot container to start
      - |
        # List all running containers to debug
        echo "📋 Currently running containers:"
        docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Image}}"
      - |
        # Check if any Discord bot container is running (more flexible search)
        if docker ps --format "{{.Names}}" | grep -E "(discord|emoji|bot)" || docker ps --format "{{.Image}}" | grep -E "(discord|emoji)"; then
          echo "✅ Discord Emoji Bot container is running"
          # Get the actual container name/ID for logs
          CONTAINER_NAME=$(docker ps --format "{{.Names}}" | grep -E "(discord|emoji|bot)" | head -1)
          if [ -z "$CONTAINER_NAME" ]; then
            CONTAINER_NAME=$(docker ps --format "{{.Names}}" | head -1)
          fi
          echo "📄 Container logs for: $CONTAINER_NAME"
          docker logs "$CONTAINER_NAME" --tail 20
        else
          echo "❌ Discord Emoji Bot container is not running"
          echo "📋 All containers:"
          docker ps -a
          exit 1
        fi
      - echo "✅ Discord Emoji Bot health check passed!"

  # Cleanup old images
  - name: cleanup
    image: docker:24-cli
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      - branch: main
    commands:
      - echo "🧹 Cleaning up old Discord Emoji Bot Docker images..."
      - docker image prune -f
      - docker images | grep discord-emoji-bot || echo "No old images to clean"
      - echo "✅ Cleanup completed!"