# Woodpecker CI Deploy Pipeline
# This pipeline handles production deployments

# Only run on main branch and tags
when:
  - event: [push, tag]
    branch: main

steps:
  # Pre-deployment checks
  - name: pre-deploy-check
    image: python:3.11-slim
    commands:
      - echo "🔍 Running pre-deployment checks..."
      - |
        if [ -z "${DISCORD_BOT_TOKEN}" ]; then
          echo "❌ DISCORD_BOT_TOKEN is required for deployment"
          exit 1
        fi
      - |
        if [ -z "${OPENAI_API_KEY}" ]; then
          echo "❌ OPENAI_API_KEY is required for deployment"
          exit 1
        fi
      - echo "✅ Environment variables validated"

  # Build production image
  - name: build-production
    image: docker:24
    commands:
      - echo "🏗️ Building production Docker image..."
      - docker build -t emoji-bot:production-${CI_COMMIT_SHA} .
      - docker tag emoji-bot:production-${CI_COMMIT_SHA} emoji-bot:production-latest
      - echo "✅ Production image built!"

  # Deploy using docker-compose
  - name: deploy-with-compose
    image: docker:24
    commands:
      - echo "🚀 Deploying with docker-compose..."
      - |
        # Install docker-compose
        apk add --no-cache curl
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      - |
        # Update the docker-compose.yml to use the new image
        sed -i "s|build: \.|image: emoji-bot:production-${CI_COMMIT_SHA}|" docker-compose.yml
      - |
        # Deploy the application
        docker-compose down || true
        docker-compose up -d
      - echo "✅ Deployment completed!"

  # Health check
  - name: health-check
    image: docker:24
    commands:
      - echo "🏥 Running health checks..."
      - sleep 30  # Wait for container to start
      - |
        # Check if container is running
        if docker ps | grep emoji-bot; then
          echo "✅ Container is running"
        else
          echo "❌ Container is not running"
          docker logs emoji-bot
          exit 1
        fi
      - echo "✅ Health check passed!"

  # Cleanup old images
  - name: cleanup
    image: docker:24
    commands:
      - echo "🧹 Cleaning up old Docker images..."
      - docker image prune -f
      - echo "✅ Cleanup completed!"

# Removed services and volumes sections due to trust level restrictions
