# Woodpecker CI Test Pipeline
# This is a simpler pipeline for testing and development

# Trigger on all events
when:
  - event: [push, pull_request, tag, manual]

steps:
  # Quick code validation
  - name: quick-test
    image: python:3.11-slim
    commands:
      - echo "🔍 Running quick validation tests..."
      - apt-get update && apt-get install -y gcc
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - python -c "import sys; sys.path.insert(0, 'src'); import discord_emoji; print('✅ Bot imports successfully')"
      - python -c "import discord; import openai; import aiohttp; from PIL import Image; print('✅ All dependencies available')"
      - echo "✅ Quick tests passed!"

  # Syntax and basic checks
  - name: syntax-check
    image: python:3.11-slim
    commands:
      - echo "🔍 Checking Python syntax..."
      - python -m py_compile src/discord_emoji.py
      - echo "✅ Syntax check passed!"

  # Docker build test
  - name: docker-build-test
    image: docker:24
    commands:
      - echo "🏗️ Testing Docker build..."
      - docker build -t emoji-bot-test:${CI_COMMIT_SHA} .
      - echo "✅ Docker build test completed!"

# Removed services and volumes sections due to trust level restrictions
